export const dependencies = [
  { name: "@gorhom/bottom-sheet", version: "^4.4.5" },
  { name: "@react-navigation/drawer", version: "^6.6.2" },
  { name: "@react-navigation/native", version: "^6.1.6" },
  { name: "@react-navigation/stack", version: "^6.3.16" },
  { name: "@tanstack/react-query", version: "^4.26.1" },
  { name: "axios", version: "^1.3.4" },
  { name: "lottie-react-native", version: "^5.1.5" },
  { name: "react", version: "18.1.0" },
  { name: "react-native", version: "0.70.6" },
  { name: "react-native-dotenv", version: "^3.4.8" },
  { name: "react-native-gesture-handler", version: "^2.9.0" },
  { name: "react-native-linear-gradient", version: "^2.6.2" },
  { name: "react-native-paper", version: "^5.2.0" },
  { name: "react-native-reanimated", version: "^2.14.4" },
  { name: "react-native-safe-area-context", version: "^4.5.0" },
  { name: "react-native-screens", version: "^3.20.0" },
  { name: "react-native-toast-notifications", version: "^3.3.1" },
  { name: "react-native-vector-icons", version: "^9.2.0" },
]
